// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_8 = "CgkI3Jncs4oGEAIQAg"; // <GPGSID>
        public const string achievement_9 = "CgkI3Jncs4oGEAIQAQ"; // <GPGSID>
        public const string leaderboard__3 = "CgkI3Jncs4oGEAIQDA"; // <GPGSID>
        public const string leaderboard__4 = "CgkI3Jncs4oGEAIQDQ"; // <GPGSID>
        public const string leaderboard = "CgkI3Jncs4oGEAIQBQ"; // <GPGSID>
        public const string leaderboard__2 = "CgkI3Jncs4oGEAIQCw"; // <GPGSID>
        public const string leaderboard__1 = "CgkI3Jncs4oGEAIQDg"; // <GPGSID>
        public const string achievement = "CgkI3Jncs4oGEAIQBA"; // <GPGSID>
        public const string achievement_7 = "CgkI3Jncs4oGEAIQAw"; // <GPGSID>

}

